/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Erlanha_Trans;

/**
 *
 * @author MyBook Hype AMD
 */
public class GUI_Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_Menu.class.getName());

    /**
     * Creates new form GUI_Menu
     */
    public GUI_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblSubJudul = new javax.swing.JLabel();
        btnDataTiket = new javax.swing.JButton();
        btnCasting = new javax.swing.JButton();
        btnTentang = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setText("ERLANHA TRANS");

        lblSubJudul.setText("Sistem Pemesanan Tiket Bus");

        btnDataTiket.setText("Data Tiket");
        btnDataTiket.addActionListener(this::btnDataTiketActionPerformed);

        btnCasting.setText("Demo Casting");
        btnCasting.addActionListener(this::btnCastingActionPerformed);

        btnTentang.setText("Tentang");
        btnTentang.addActionListener(this::btnTentangActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSubJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDataTiket))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCasting))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTentang))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKeluar)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubJudul)
                .addGap(18, 18, 18)
                .addComponent(btnDataTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCasting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTentang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTiketActionPerformed
        GUI_Trans form = new GUI_Trans();
        form.setVisible(true);
    }//GEN-LAST:event_btnDataTiketActionPerformed

    private void btnCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCastingActionPerformed
         Bus bus = new VIP(
            "Erlanha_Trans",
            "Jakarta",
            250000);

    String hasil = "";

    // UPCASTING
    hasil += "=== UPCASTING ===\n\n";
    hasil += bus.tampilkanInfo();

    // DOWNCASTING
    if(bus instanceof VIP){

        VIP vip = (VIP) bus;

        hasil += "\n\n=== DOWNCASTING ===\n";
        hasil += "Fasilitas : "
                + vip.getFasilitas();
    }

    javax.swing.JOptionPane.showMessageDialog(
            this,
            hasil);
    }//GEN-LAST:event_btnCastingActionPerformed

    private void btnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentangActionPerformed
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "ERLANHA TRANS\n\n"
            + "Project OOP Java\n"
            + "Menggunakan:\n"
            + "- Encapsulation\n"
            + "- Inheritance\n"
            + "- Polymorphism\n"
            + "- Abstraction\n"
            + "- Upcasting\n"
            + "- Downcasting");
    }//GEN-LAST:event_btnTentangActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasting;
    private javax.swing.JButton btnDataTiket;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTentang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblSubJudul;
    // End of variables declaration//GEN-END:variables
}
